export default {
  "login": "ksushant6566",
  "id": 50081688,
  "node_id": "MDQ6VXNlcjUwMDgxNjg4",
  "avatar_url": "https://avatars0.githubusercontent.com/u/50081688?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ksushant6566",
  "html_url": "https://github.com/ksushant6566",
  "followers_url": "https://api.github.com/users/ksushant6566/followers",
  "following_url": "https://api.github.com/users/ksushant6566/following{/other_user}",
  "gists_url": "https://api.github.com/users/ksushant6566/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ksushant6566/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ksushant6566/subscriptions",
  "organizations_url": "https://api.github.com/users/ksushant6566/orgs",
  "repos_url": "https://api.github.com/users/ksushant6566/repos",
  "events_url": "https://api.github.com/users/ksushant6566/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ksushant6566/received_events",
  "type": "User",
  "site_admin": false,
  "name": "sushant ",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2019-04-28T16:43:22Z",
  "updated_at": "2020-08-13T12:09:22Z"
};